// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkihkrhavgrziemldesi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraWhrcmhhdmdyemllbWxkZXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzIyMjYsImV4cCI6MjA2NzMwODIyNn0.HXvD0zEF_B2LApYUC3RBC5TLrbjQi6yOdafwCYk-cIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});